---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: haproxy-ingress-lb-service
spec:
{{ if (.Values.cloudProvider.create_loadbalancer | default false) }}
  type: LoadBalancer
{{ else }}
  type: NodePort
{{ end }}
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: https2
    port: 6443
    targetPort: 6443
  selector:
    run: haproxy-ingress
