apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-elasticsearch
spec:
{{- if eq .Values.storageClassProvisioner "hostPath" }}
  template:
    spec:
      volumes:
        - name: data
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.hostPathCustomPaths.elasticsearch }}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.pvStorageSize.small.elasticsearch }}
        storageClassName: {{ .Values.storageClassName }}
{{- end }}
