sysdig:
  default:
    username: test@sysdig.com
    password: {{ randAlphaNum 16 }}
  mysql:
    password: {{ randAlphaNum 16 }}
    root:
      password: {{ randAlphaNum 16 }}
    secure:
      password: {{ randAlphaNum 16 }}
  redis:
    password: {{ randAlphaNum 16 }}
  secure:
    admin:
      password: {{ randAlphaNum 16 }}
    db:
      password: {{ randAlphaNum 16 }}
  searchguard:
    adminUser:
      password: {{ randAlphaNum 16 }}
    readonly:
      password: {{ randAlphaNum 16 }}
